version: '3.1'
services:
  db:
    image: postgres:9.5
    container_name: polyclinic-postgres
    restart: always
    environment:
      POSTGRES_USER: ${RDS_USERNAME:root}
      POSTGRES_PASSWORD: ${RDS_PASSWORD:}
      POSTGRES_DB: polyclinik
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - /var/lib/postgresql/data/pgdata
    command: [ "postgres", "-c", "log_statement=all" ]
    ports:
      - 5432:5432
    networks:
      - polyclinic-app-network

  app-server:
    container_name: polyclinic-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://${RDS_HOSTNAME:localhost}:${RDS_PORT:5432}/${RDS_DB_NAME:springtodo}
      SPRING_DATASOURCE_USERNAME: ${RDS_USERNAME:root}
      SPRING_DATASOURCE_PASSWORD: ${RDS_PASSWORD:}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - polyclinic-app-network
volumes:
  db-data:

networks:
  polyclinic-app-network:
    driver: bridge