server:
  port: 5000

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    initialization-mode: always
    username: ${RDS_USERNAME:root}
    password: ${RDS_PASSWORD:}
    url: jdbc:postgresql://${RDS_HOSTNAME:localhost}:${RDS_PORT:5432}/${RDS_DB_NAME:springtodo}

jpa:
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true
      temp:
        use_jdbc_metadata_defaults: false
    javax:
      persistence:
        validation:
          mode: none
    show-sql: true