server:
  port: 5000

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    initialization-mode: always
    username: postgres
    password: lashchenkovaSQL#2022
    url: jdbc:postgresql://awseb-e-2ftxiapsqm-stack-awsebrdsdatabase-or2rwuc2eblf.cljrfxobcy27.us-east-1.rds.amazonaws.com:5432/ebdb

jpa:
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true
      temp:
        use_jdbc_metadata_defaults: false
    javax:
      persistence:
        validation:
          mode: none
    show-sql: true