server:
  port: 9000

spring:
  datasource:
    url: jdbc:h2:mem:mydatabase;
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    properties:
      hibernate.ddl-auto: create-drop
      hibernate.hbm2ddl.import_files: >
        db/doctor_insert_script.sql,
        db/hospital_insert_script.sql,
        db/patient_insert_script.sql
      hibernate.format_sql: true